# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:1.15
    restart: unless-stopped
    # маршрутизируем порты
    ports:
    - "${NGINX_HOST_HTTP_PORT}:80"
    - "${NGINX_HOST_HTTPS_PORT}:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
    - ./services/nginx:/etc/nginx/conf.d
    - "${APP_HOST_PATH}:/var/www"
    - ./data/nginx:/var/log/nginx

  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: services/php
    restart: unless-stopped
    # монтируем директорию с проектами
    volumes:
    - "${APP_HOST_PATH}:/var/www"

  memcached:
    image: bitnami/memcached:1.5.12
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    volumes:
      - ./services/memcached/memcached.conf:/etc/memcached.conf
      - ./data/memcached/memcached.log:/var/log/memcached.log

  mariadb:
    image: mariadb:10.3
    restart: unless-stopped
    ports:
    - "${MYSQL_HOST_PORT}:3306"
    volumes:
    - ./data/mariadb:/var/lib/mysql
    - "${APP_HOST_PATH}/sql/main.sql:/docker-entrypoint-initdb.d/01-main.sql"
    - ./migrations/02-create-users.sql:/docker-entrypoint-initdb.d/02-create-users.sql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
    - mariadb
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
    - "${PMA_HOST_PORT}:80"
    volumes:
    - ./services/phpmyadmin:/etc/phpmyadmin

  xbt_tracker:
    image: kauden/xbt_tracker:latest
#    volumes:
#      - ./images/xbt_tracker/xbt_tracker.conf:/opt/xbt_tracker/xbt_tracker.conf
    depends_on:
    - mariadb

  sphinx:
    build: services/sphinx
    restart: unless-stopped
    depends_on:
    - mariadb
    volumes:
      - ./data/sphinx:/var/log/sphinxsearch
#    - ./sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
#    - ./sphinxsearch:/var/lib/sphinxsearch/data
